// src/lib/components/CommandPalette.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { goto } from "$app/navigation";
  import {
    Home,
    Briefcase,
    FolderGit2,
    Heart,
    Mail,
    Search,
    FileText,
  } from "lucide-svelte";
  import { getExperience, getProjects } from "$lib/content";
  import type { Component } from "svelte";

  let { open = $bindable(false) }: { open?: boolean } = $props();

  let query = $state("");

  const NAVIGATION_ITEMS: {
    id: string;
    label: string;
    path: string;
    icon: Component;
  }[] = [
    { id: "home", label: "Home", path: "/", icon: Home },
    {
      id: "experience",
      label: "Experience",
      path: "/experience",
      icon: Briefcase,
    },
    { id: "projects", label: "Projects", path: "/projects", icon: FolderGit2 },
    { id: "interests", label: "Interests", path: "/interests", icon: Heart },
    { id: "contact", label: "Contact", path: "/contact", icon: Mail },
  ];

  const experience = getExperience();
  const projects = getProjects();

  const q = $derived(query.trim().toLowerCase());

  const navFiltered = $derived(
    NAVIGATION_ITEMS.filter(
      (n) =>
        !q ||
        n.label.toLowerCase().includes(q) ||
        n.path.includes(q),
    ),
  );

  const expFiltered = $derived(
    experience.filter(
      (e) =>
        !q ||
        e.company.toLowerCase().includes(q) ||
        e.role.toLowerCase().includes(q),
    ),
  );

  const projFiltered = $derived(
    projects.filter(
      (p) =>
        !q ||
        p.title.toLowerCase().includes(q) ||
        p.technologies.some((t) => t.toLowerCase().includes(q)),
    ),
  );

  function select(path: string) {
    open = false;
    query = "";
    goto(path);
  }

  function onKeydown(e: KeyboardEvent) {
    if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
      e.preventDefault();
      open = !open;
    }
    if (e.key === "Escape") open = false;
  }

  onMount(() => {
    window.addEventListener("keydown", onKeydown);
    return () => window.removeEventListener("keydown", onKeydown);
  });
</script>

{#if open}
  <button
    type="button"
    class="fixed inset-0 z-[100] bg-background/80 backdrop-blur-sm"
    aria-label="Close"
    onclick={() => (open = false)}
  ></button>
  <div
    class="fixed left-1/2 top-[20%] z-[101] w-[min(100%-2rem,32rem)] -translate-x-1/2 rounded-lg border bg-popover p-0 shadow-lg"
    role="dialog"
    aria-modal="true"
  >
    <div class="flex items-center border-b px-3">
      <Search class="mr-2 h-4 w-4 shrink-0 text-muted-foreground" />
      <input
        class="flex h-12 w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground"
        placeholder="Search pages, projects, experience..."
        bind:value={query}
        data-testid="input-command-search"
      />
    </div>
    <div class="max-h-[60vh] overflow-y-auto p-2 text-sm">
      {#if navFiltered.length + expFiltered.length + projFiltered.length === 0}
        <p class="px-2 py-6 text-center text-muted-foreground">No results found.</p>
      {:else}
        {#if navFiltered.length}
          <p class="px-2 py-1 text-xs font-medium text-muted-foreground">Navigation</p>
          {#each navFiltered as item (item.id)}
            {@const Icon = item.icon}
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-md px-2 py-2 text-left hover:bg-muted"
              onclick={() => select(item.path)}
              data-testid="command-item-nav-{item.id}"
            >
              <Icon class="h-4 w-4" />
              <span>{item.label}</span>
            </button>
          {/each}
        {/if}
        {#if expFiltered.length}
          <p class="mt-2 px-2 py-1 text-xs font-medium text-muted-foreground">
            Experience
          </p>
          {#each expFiltered as exp (exp.id)}
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-md px-2 py-2 text-left hover:bg-muted"
              onclick={() => select(`/experience#${exp.id}`)}
              data-testid="command-item-exp-{exp.id}"
            >
              <Briefcase class="h-4 w-4 shrink-0" />
              <span class="flex flex-col">
                <span>{exp.role}</span>
                <span class="text-xs text-muted-foreground">{exp.company}</span>
              </span>
            </button>
          {/each}
        {/if}
        {#if projFiltered.length}
          <p class="mt-2 px-2 py-1 text-xs font-medium text-muted-foreground">Projects</p>
          {#each projFiltered as project (project.id)}
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded-md px-2 py-2 text-left hover:bg-muted"
              onclick={() => select(`/projects#${project.id}`)}
              data-testid="command-item-proj-{project.id}"
            >
              <FolderGit2 class="h-4 w-4 shrink-0" />
              <span class="flex flex-col">
                <span>{project.title}</span>
                <span class="text-xs text-muted-foreground"
                  >{project.technologies.slice(0, 3).join(", ")}</span
                >
              </span>
            </button>
          {/each}
        {/if}
        <p class="mt-2 px-2 py-1 text-xs font-medium text-muted-foreground">
          Quick Actions
        </p>
        <button
          type="button"
          class="flex w-full items-center gap-2 rounded-md px-2 py-2 text-left hover:bg-muted"
          onclick={() => {
            open = false;
            window.open("/resume.pdf", "_blank");
          }}
          data-testid="command-item-resume"
        >
          <FileText class="h-4 w-4" />
          <span>View Resume</span>
        </button>
      {/if}
    </div>
  </div>
{/if}

// client/src/components/CommandPalette.tsx
import { useEffect, useState, useCallback } from "react";
import { useLocation } from "wouter";
import { motion, AnimatePresence } from "framer-motion";
import {
  Home,
  Briefcase,
  FolderGit2,
  Heart,
  Mail,
  Search,
  FileText,
} from "lucide-react";
import {
  CommandDialog,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from "@/components/ui/command";
import { useTheme } from "./ThemeProvider";
import { getExperience, getProjects } from "@/lib/content";

const NAVIGATION_ITEMS = [
  { id: "home", label: "Home", path: "/", icon: Home },
  { id: "experience", label: "Experience", path: "/experience", icon: Briefcase },
  { id: "projects", label: "Projects", path: "/projects", icon: FolderGit2 },
  { id: "interests", label: "Interests", path: "/interests", icon: Heart },
  { id: "contact", label: "Contact", path: "/contact", icon: Mail },
];

interface CommandPaletteProps {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
}

export function CommandPalette({ open: controlledOpen, onOpenChange }: CommandPaletteProps) {
  const [internalOpen, setInternalOpen] = useState(false);
  const [, setLocation] = useLocation();
  const { prefersReducedMotion } = useTheme();

  const open = controlledOpen !== undefined ? controlledOpen : internalOpen;
  const setOpen = onOpenChange || setInternalOpen;

  useEffect(() => {
    const down = (e: KeyboardEvent) => {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        setOpen(!open);
      }
    };

    document.addEventListener("keydown", down);
    return () => document.removeEventListener("keydown", down);
  }, [open, setOpen]);

  const handleSelect = useCallback(
    (path: string) => {
      setOpen(false);
      setLocation(path);
    },
    [setOpen, setLocation]
  );

  const experience = getExperience();
  const projects = getProjects();

  return (
    <CommandDialog open={open} onOpenChange={setOpen}>
      <CommandInput placeholder="Search pages, projects, experience..." data-testid="input-command-search" />
      <CommandList>
        <CommandEmpty>No results found.</CommandEmpty>

        <CommandGroup heading="Navigation">
          {NAVIGATION_ITEMS.map((item) => (
            <CommandItem
              key={item.id}
              value={`nav-${item.label}`}
              onSelect={() => handleSelect(item.path)}
              data-testid={`command-item-nav-${item.id}`}
            >
              <item.icon className="mr-2 h-4 w-4" />
              <span>{item.label}</span>
            </CommandItem>
          ))}
        </CommandGroup>

        <CommandSeparator />

        <CommandGroup heading="Experience">
          {experience.map((exp) => (
            <CommandItem
              key={exp.id}
              value={`exp-${exp.company}-${exp.role}`}
              onSelect={() => handleSelect(`/experience#${exp.id}`)}
              data-testid={`command-item-exp-${exp.id}`}
            >
              <Briefcase className="mr-2 h-4 w-4" />
              <div className="flex flex-col">
                <span>{exp.role}</span>
                <span className="text-xs text-muted-foreground">{exp.company}</span>
              </div>
            </CommandItem>
          ))}
        </CommandGroup>

        <CommandSeparator />

        <CommandGroup heading="Projects">
          {projects.map((project) => (
            <CommandItem
              key={project.id}
              value={`proj-${project.title}`}
              onSelect={() => handleSelect(`/projects#${project.id}`)}
              data-testid={`command-item-proj-${project.id}`}
            >
              <FolderGit2 className="mr-2 h-4 w-4" />
              <div className="flex flex-col">
                <span>{project.title}</span>
                <span className="text-xs text-muted-foreground">
                  {project.technologies.slice(0, 3).join(", ")}
                </span>
              </div>
            </CommandItem>
          ))}
        </CommandGroup>

        <CommandSeparator />

        <CommandGroup heading="Quick Actions">
          <CommandItem
            value="resume"
            onSelect={() => {
              setOpen(false);
              window.open("/resume.pdf", "_blank");
            }}
            data-testid="command-item-resume"
          >
            <FileText className="mr-2 h-4 w-4" />
            <span>View Resume</span>
          </CommandItem>
        </CommandGroup>
      </CommandList>
    </CommandDialog>
  );
}

export function CommandPaletteTrigger({ onClick }: { onClick: () => void }) {
  const isMac = typeof navigator !== "undefined" && navigator.platform.toUpperCase().indexOf("MAC") >= 0;

  return (
    <button
      onClick={onClick}
      className="hidden md:flex items-center gap-2 px-3 py-1.5 text-sm text-muted-foreground border rounded-md hover-elevate transition-colors"
      data-testid="button-command-trigger"
      aria-label="Open command palette"
    >
      <Search className="h-3.5 w-3.5" />
      <span>Search...</span>
      <kbd className="pointer-events-none hidden h-5 select-none items-center gap-1 rounded border bg-muted px-1.5 font-mono text-[10px] font-medium text-muted-foreground sm:flex">
        {isMac ? "⌘" : "Ctrl"}K
      </kbd>
    </button>
  );
}
