// client/src/components/ImageLightbox.tsx
import { useEffect, useCallback } from "react";
import { createPortal } from "react-dom";
import { motion, AnimatePresence } from "framer-motion";
import { X, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { type ProjectMedia } from "@/lib/content";

interface ImageLightboxProps {
  isOpen: boolean;
  onClose: () => void;
  media: ProjectMedia[];
  currentIndex: number;
  onIndexChange: (index: number) => void;
}

export function ImageLightbox({
  isOpen,
  onClose,
  media,
  currentIndex,
  onIndexChange,
}: ImageLightboxProps) {
  const handlePrevious = useCallback(() => {
    onIndexChange(currentIndex > 0 ? currentIndex - 1 : media.length - 1);
  }, [currentIndex, media.length, onIndexChange]);

  const handleNext = useCallback(() => {
    onIndexChange(currentIndex < media.length - 1 ? currentIndex + 1 : 0);
  }, [currentIndex, media.length, onIndexChange]);

  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (!isOpen) return;
      switch (e.key) {
        case "Escape":
          onClose();
          break;
        case "ArrowLeft":
          handlePrevious();
          break;
        case "ArrowRight":
          handleNext();
          break;
      }
    },
    [isOpen, onClose, handlePrevious, handleNext]
  );

  useEffect(() => {
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [handleKeyDown]);

  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [isOpen]);

  const currentMedia = media[currentIndex];

  const getYouTubeEmbedUrl = (url: string) => {
    const videoId = url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\s]+)/)?.[1];
    return videoId ? `https://www.youtube.com/embed/${videoId}?autoplay=1` : url;
  };

  const renderMedia = () => {
    if (!currentMedia) return null;

    switch (currentMedia.type) {
      case "video":
        return (
          <video
            src={currentMedia.url}
            controls
            muted
            playsInline
            preload="metadata"
            className="max-w-full max-h-[85vh] rounded-lg"
            data-testid="video-lightbox-player"
          />
        );
      case "youtube":
        return (
          <iframe
            src={getYouTubeEmbedUrl(currentMedia.url)}
            className="w-[80vw] h-[45vw] max-w-[1200px] max-h-[675px] rounded-lg"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
            data-testid="youtube-lightbox-player"
          />
        );
      case "iframe":
        return (
          <iframe
            src={currentMedia.url}
            className="w-[90vw] h-[80vh] max-w-[1400px] rounded-lg bg-white"
            data-testid="iframe-lightbox-player"
          />
        );
      case "image":
      default:
        return (
          <img
            src={currentMedia.url}
            alt={currentMedia.caption || `Media ${currentIndex + 1}`}
            className="max-w-full max-h-[85vh] rounded-lg object-contain"
            data-testid="image-lightbox-display"
          />
        );
    }
  };

  const lightboxContent = (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          className="fixed inset-0 z-[100] flex items-center justify-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          data-testid="image-lightbox"
        >
          <motion.div
            className="absolute inset-0 bg-black/90"
            onClick={onClose}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          />

          <Button
            variant="ghost"
            size="icon"
            className="absolute top-4 right-4 z-10 text-white hover:bg-white/20"
            onClick={onClose}
            data-testid="button-lightbox-close"
          >
            <X className="h-6 w-6" />
          </Button>

          {media.length > 1 && (
            <>
              <Button
                variant="ghost"
                size="icon"
                className="absolute left-4 z-10 text-white hover:bg-white/20"
                onClick={handlePrevious}
                data-testid="button-lightbox-previous"
              >
                <ChevronLeft className="h-8 w-8" />
              </Button>
              <Button
                variant="ghost"
                size="icon"
                className="absolute right-4 z-10 text-white hover:bg-white/20"
                onClick={handleNext}
                data-testid="button-lightbox-next"
              >
                <ChevronRight className="h-8 w-8" />
              </Button>
            </>
          )}

          <motion.div
            className="relative z-10 flex flex-col items-center max-w-[100vw] max-h-[100vh] p-4"
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.9, opacity: 0 }}
            transition={{ duration: 0.2 }}
          >
            {renderMedia()}
            {currentMedia?.caption && (
              <p className="mt-3 text-white/80 text-sm text-center max-w-lg">
                {currentMedia.caption}
              </p>
            )}
          </motion.div>

          {media.length > 1 && (
            <div className="absolute bottom-6 left-1/2 -translate-x-1/2 flex items-center gap-2 z-10">
              {media.map((_, index) => (
                <button
                  key={index}
                  className={`w-2 h-2 rounded-full transition-colors ${
                    index === currentIndex
                      ? "bg-white"
                      : "bg-white/40 hover:bg-white/60"
                  }`}
                  onClick={() => onIndexChange(index)}
                  data-testid={`button-lightbox-dot-${index}`}
                />
              ))}
            </div>
          )}
        </motion.div>
      )}
    </AnimatePresence>
  );

  return typeof document !== "undefined"
    ? createPortal(lightboxContent, document.body)
    : lightboxContent;
}

// src/lib/components/ImageLightbox.svelte
<script lang="ts">
  import { browser } from "$app/environment";
  import { X, ChevronLeft, ChevronRight } from "lucide-svelte";
  import Button from "$lib/ui/Button.svelte";
  import type { ProjectMedia } from "$lib/content";

  let {
    open = $bindable(false),
    media,
    currentIndex = $bindable(0),
  }: {
    open?: boolean;
    media: ProjectMedia[];
    currentIndex?: number;
  } = $props();

  function prev() {
    currentIndex =
      currentIndex > 0 ? currentIndex - 1 : media.length - 1;
  }

  function next() {
    currentIndex =
      currentIndex < media.length - 1 ? currentIndex + 1 : 0;
  }

  function onKey(e: KeyboardEvent) {
    if (!open) return;
    if (e.key === "Escape") open = false;
    if (e.key === "ArrowLeft") prev();
    if (e.key === "ArrowRight") next();
  }

  $effect(() => {
    if (!browser) return;
    if (open) document.body.style.overflow = "hidden";
    else document.body.style.overflow = "";
    return () => {
      if (browser) document.body.style.overflow = "";
    };
  });

  $effect(() => {
    if (!browser) return;
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  });

  function youtubeEmbed(url: string) {
    const videoId = url.match(
      /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\s]+)/,
    )?.[1];
    return videoId
      ? `https://www.youtube.com/embed/${videoId}?autoplay=1`
      : url;
  }

  const current = $derived(media[currentIndex]);
</script>

{#if open && current}
  <div
    class="fixed inset-0 z-[100] flex items-center justify-center"
    data-testid="image-lightbox"
  >
    <button
      type="button"
      class="absolute inset-0 bg-black/90"
      aria-label="Close lightbox"
      onclick={() => (open = false)}
    ></button>
    <Button
      variant="ghost"
      size="icon"
      class="absolute right-4 top-4 z-10 text-white hover:bg-white/20"
      onclick={() => (open = false)}
      data-testid="button-lightbox-close"
    >
      <X class="h-6 w-6" />
    </Button>
    {#if media.length > 1}
      <Button
        variant="ghost"
        size="icon"
        class="absolute left-4 z-10 text-white hover:bg-white/20"
        onclick={prev}
        data-testid="button-lightbox-previous"
      >
        <ChevronLeft class="h-8 w-8" />
      </Button>
      <Button
        variant="ghost"
        size="icon"
        class="absolute right-4 z-10 text-white hover:bg-white/20"
        onclick={next}
        data-testid="button-lightbox-next"
      >
        <ChevronRight class="h-8 w-8" />
      </Button>
    {/if}
    <div
      class="relative z-10 flex max-h-[100vh] max-w-[100vw] flex-col items-center p-4"
    >
      {#if current.type === "video"}
        <video
          src={current.url}
          controls
          muted
          playsinline
          preload="metadata"
          class="max-h-[85vh] max-w-full rounded-lg"
          data-testid="video-lightbox-player"
        ></video>
      {:else if current.type === "youtube"}
        <iframe
          src={youtubeEmbed(current.url)}
          class="h-[45vw] max-h-[675px] w-[80vw] max-w-[1200px] rounded-lg"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
          title="YouTube"
          data-testid="youtube-lightbox-player"
        ></iframe>
      {:else if current.type === "iframe"}
        <iframe
          src={current.url}
          class="h-[80vh] w-[90vw] max-w-[1400px] rounded-lg bg-white"
          title="Embed"
          data-testid="iframe-lightbox-player"
        ></iframe>
      {:else}
        <img
          src={current.url}
          alt={current.caption || `Media ${currentIndex + 1}`}
          class="max-h-[85vh] max-w-full rounded-lg object-contain"
          data-testid="image-lightbox-display"
        />
      {/if}
      {#if current.caption}
        <p class="mt-3 max-w-lg text-center text-sm text-white/80">
          {current.caption}
        </p>
      {/if}
    </div>
    {#if media.length > 1}
      <div
        class="absolute bottom-6 left-1/2 z-10 flex -translate-x-1/2 items-center gap-2"
      >
        {#each media as _, index (index)}
          <button
            type="button"
            class="h-2 w-2 rounded-full transition-colors {index === currentIndex
              ? 'bg-white'
              : 'bg-white/40 hover:bg-white/60'}"
            onclick={() => (currentIndex = index)}
            data-testid="button-lightbox-dot-{index}"
            aria-label="Go to slide {index + 1}"
          ></button>
        {/each}
      </div>
    {/if}
  </div>
{/if}
