// client/src/components/ThemeToggle.tsx
import { Sun, Moon } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { useTheme } from "./ThemeProvider";

export function ThemeToggle() {
  const { theme, toggleTheme, prefersReducedMotion } = useTheme();
  const isDark = theme === "dark";

  const iconVariants = {
    initial: prefersReducedMotion
      ? { opacity: 0 }
      : { opacity: 0, rotate: -90, scale: 0 },
    animate: prefersReducedMotion
      ? { opacity: 1 }
      : { opacity: 1, rotate: 0, scale: 1 },
    exit: prefersReducedMotion
      ? { opacity: 0 }
      : { opacity: 0, rotate: 90, scale: 0 },
  };

  const transition = prefersReducedMotion
    ? { duration: 0 }
    : { duration: 0.2, ease: "easeInOut" };

  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={toggleTheme}
      aria-label={isDark ? "Switch to light mode" : "Switch to dark mode"}
      data-testid="button-theme-toggle"
      className="relative overflow-visible"
    >
      <AnimatePresence mode="wait" initial={false}>
        {isDark ? (
          <motion.div
            key="moon"
            variants={iconVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={transition}
            className="absolute inset-0 flex items-center justify-center"
          >
            <Moon className="h-5 w-5" />
          </motion.div>
        ) : (
          <motion.div
            key="sun"
            variants={iconVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            transition={transition}
            className="absolute inset-0 flex items-center justify-center"
          >
            <Sun className="h-5 w-5" />
          </motion.div>
        )}
      </AnimatePresence>
      <span className="sr-only">
        {isDark ? "Switch to light mode" : "Switch to dark mode"}
      </span>
    </Button>
  );
}

// src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { Moon, Sun } from "lucide-svelte";
  import Button from "$lib/ui/Button.svelte";
  import { themeStore, toggleTheme } from "$lib/stores/theme";
</script>

<Button
  variant="ghost"
  size="icon"
  class="h-9 w-9"
  onclick={() => toggleTheme()}
  aria-label="Toggle theme"
  data-testid="button-theme-toggle"
>
  {#if $themeStore === "dark"}
    <Sun class="h-4 w-4" />
  {:else}
    <Moon class="h-4 w-4" />
  {/if}
</Button>
